# docker build -f Dockerfile.iis.nano -t paulgilchrist/angular2template:iisnano .
# docker run paulgilchrist/angular2template:iisnano
# docker inspect <containerID>
# Test on http://<containerIP>:80
FROM microsoft/iis:nanoserver
COPY build C:/inetpub/wwwroot
RUN "del C:\inetpub\wwwroot\web.config"
