# Ensure you have setup Docker and created a NodeJS container
#    See dockerReadMe.md
# docker build -f Dockerfile.node.nano -t paulgilchrist/angular2template:nodenano .
# docker run -d -p 80:3000 paulgilchrist/angular2template:nodenano
# docker inspect <containerId>
# Test on http://<containerIP>:3000
# docker rm -f <containerID>
FROM paulgilchrist/node:nano
RUN mkdir build
COPY build /build
WORKDIR /build
# RUN npm install
CMD [ "node", "server.js" ]